# Configurações da Aplicação
spring.application.name=SecureLoginPUC

# Credenciais de Acesso (Login)
app.user.username=joao
app.user.password=4321
app.admin.username=admin
app.admin.password=1234

# Configurações de E-mail (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# O e-mail que fará o envio das mensagens
spring.mail.username=jplisboa.dev@gmail.com
spring.mail.password=dsyj jlle jkgc nsvy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true